-- SINIESTRO Inserts
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (1, 'Colisión de vehículo por detrás en intersección Nro. 1');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (2, 'Robo parcial de accesorios de vehículo en estacionamiento Nro. 2');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (3, 'Inundación de sótano por colapso de tubería de aguas lluvias Nro. 3');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (4, 'Rotura de cristales exteriores por vandalismo Nro. 4');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (5, 'Fractura de tobillo del asegurado en accidente doméstico Nro. 5');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (6, 'Fallecimiento natural del asegurado principal Nro. 6');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (7, 'Incendio parcial en área de cocina por cortocircuito Nro. 7');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (8, 'Daños por agua debido a filtración en el techo Nro. 8');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (9, 'Pérdida total del vehículo por colisión y vuelco Nro. 9');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (10, 'Robo con violencia de pertenencias personales en vía pública Nro. 10');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (11, 'Tratamiento de emergencia por intoxicación alimentaria Nro. 11');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (12, 'Cirugía programada de apendicitis Nro. 12');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (13, 'Daños estructurales menores por sismo Nro. 13');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (14, 'Daño a equipos electrónicos por fluctuación de voltaje Nro. 14');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (15, 'Lesión por caída en las instalaciones comerciales aseguradas Nro. 15');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (16, 'Colisión de vehículo por detrás en intersección Nro. 16');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (17, 'Robo parcial de accesorios de vehículo en estacionamiento Nro. 17');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (18, 'Inundación de sótano por colapso de tubería de aguas lluvias Nro. 18');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (19, 'Rotura de cristales exteriores por vandalismo Nro. 19');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (20, 'Fractura de tobillo del asegurado en accidente doméstico Nro. 20');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (21, 'Fallecimiento natural del asegurado principal Nro. 21');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (22, 'Incendio parcial en área de cocina por cortocircuito Nro. 22');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (23, 'Daños por agua debido a filtración en el techo Nro. 23');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (24, 'Pérdida total del vehículo por colisión y vuelco Nro. 24');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (25, 'Robo con violencia de pertenencias personales en vía pública Nro. 25');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (26, 'Tratamiento de emergencia por intoxicación alimentaria Nro. 26');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (27, 'Cirugía programada de apendicitis Nro. 27');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (28, 'Daños estructurales menores por sismo Nro. 28');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (29, 'Daño a equipos electrónicos por fluctuación de voltaje Nro. 29');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (30, 'Lesión por caída en las instalaciones comerciales aseguradas Nro. 30');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (31, 'Colisión de vehículo por detrás en intersección Nro. 31');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (32, 'Robo parcial de accesorios de vehículo en estacionamiento Nro. 32');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (33, 'Inundación de sótano por colapso de tubería de aguas lluvias Nro. 33');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (34, 'Rotura de cristales exteriores por vandalismo Nro. 34');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (35, 'Fractura de tobillo del asegurado en accidente doméstico Nro. 35');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (36, 'Fallecimiento natural del asegurado principal Nro. 36');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (37, 'Incendio parcial en área de cocina por cortocircuito Nro. 37');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (38, 'Daños por agua debido a filtración en el techo Nro. 38');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (39, 'Pérdida total del vehículo por colisión y vuelco Nro. 39');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (40, 'Robo con violencia de pertenencias personales en vía pública Nro. 40');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (41, 'Tratamiento de emergencia por intoxicación alimentaria Nro. 41');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (42, 'Cirugía programada de apendicitis Nro. 42');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (43, 'Daños estructurales menores por sismo Nro. 43');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (44, 'Daño a equipos electrónicos por fluctuación de voltaje Nro. 44');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (45, 'Lesión por caída en las instalaciones comerciales aseguradas Nro. 45');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (46, 'Colisión de vehículo por detrás en intersección Nro. 46');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (47, 'Robo parcial de accesorios de vehículo en estacionamiento Nro. 47');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (48, 'Inundación de sótano por colapso de tubería de aguas lluvias Nro. 48');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (49, 'Rotura de cristales exteriores por vandalismo Nro. 49');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (50, 'Fractura de tobillo del asegurado en accidente doméstico Nro. 50');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (51, 'Fallecimiento natural del asegurado principal Nro. 51');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (52, 'Incendio parcial en área de cocina por cortocircuito Nro. 52');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (53, 'Daños por agua debido a filtración en el techo Nro. 53');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (54, 'Pérdida total del vehículo por colisión y vuelco Nro. 54');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (55, 'Robo con violencia de pertenencias personales en vía pública Nro. 55');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (56, 'Tratamiento de emergencia por intoxicación alimentaria Nro. 56');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (57, 'Cirugía programada de apendicitis Nro. 57');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (58, 'Daños estructurales menores por sismo Nro. 58');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (59, 'Daño a equipos electrónicos por fluctuación de voltaje Nro. 59');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (60, 'Lesión por caída en las instalaciones comerciales aseguradas Nro. 60');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (61, 'Colisión de vehículo por detrás en intersección Nro. 61');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (62, 'Robo parcial de accesorios de vehículo en estacionamiento Nro. 62');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (63, 'Inundación de sótano por colapso de tubería de aguas lluvias Nro. 63');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (64, 'Rotura de cristales exteriores por vandalismo Nro. 64');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (65, 'Fractura de tobillo del asegurado en accidente doméstico Nro. 65');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (66, 'Fallecimiento natural del asegurado principal Nro. 66');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (67, 'Incendio parcial en área de cocina por cortocircuito Nro. 67');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (68, 'Daños por agua debido a filtración en el techo Nro. 68');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (69, 'Pérdida total del vehículo por colisión y vuelco Nro. 69');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (70, 'Robo con violencia de pertenencias personales en vía pública Nro. 70');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (71, 'Tratamiento de emergencia por intoxicación alimentaria Nro. 71');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (72, 'Cirugía programada de apendicitis Nro. 72');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (73, 'Daños estructurales menores por sismo Nro. 73');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (74, 'Daño a equipos electrónicos por fluctuación de voltaje Nro. 74');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (75, 'Lesión por caída en las instalaciones comerciales aseguradas Nro. 75');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (76, 'Colisión de vehículo por detrás en intersección Nro. 76');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (77, 'Robo parcial de accesorios de vehículo en estacionamiento Nro. 77');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (78, 'Inundación de sótano por colapso de tubería de aguas lluvias Nro. 78');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (79, 'Rotura de cristales exteriores por vandalismo Nro. 79');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (80, 'Fractura de tobillo del asegurado en accidente doméstico Nro. 80');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (81, 'Fallecimiento natural del asegurado principal Nro. 81');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (82, 'Incendio parcial en área de cocina por cortocircuito Nro. 82');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (83, 'Daños por agua debido a filtración en el techo Nro. 83');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (84, 'Pérdida total del vehículo por colisión y vuelco Nro. 84');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (85, 'Robo con violencia de pertenencias personales en vía pública Nro. 85');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (86, 'Tratamiento de emergencia por intoxicación alimentaria Nro. 86');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (87, 'Cirugía programada de apendicitis Nro. 87');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (88, 'Daños estructurales menores por sismo Nro. 88');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (89, 'Daño a equipos electrónicos por fluctuación de voltaje Nro. 89');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (90, 'Lesión por caída en las instalaciones comerciales aseguradas Nro. 90');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (91, 'Colisión de vehículo por detrás en intersección Nro. 91');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (92, 'Robo parcial de accesorios de vehículo en estacionamiento Nro. 92');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (93, 'Inundación de sótano por colapso de tubería de aguas lluvias Nro. 93');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (94, 'Rotura de cristales exteriores por vandalismo Nro. 94');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (95, 'Fractura de tobillo del asegurado en accidente doméstico Nro. 95');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (96, 'Fallecimiento natural del asegurado principal Nro. 96');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (97, 'Incendio parcial en área de cocina por cortocircuito Nro. 97');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (98, 'Daños por agua debido a filtración en el techo Nro. 98');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (99, 'Pérdida total del vehículo por colisión y vuelco Nro. 99');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (100, 'Robo con violencia de pertenencias personales en vía pública Nro. 100');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (101, 'Tratamiento de emergencia por intoxicación alimentaria Nro. 101');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (102, 'Cirugía programada de apendicitis Nro. 102');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (103, 'Daños estructurales menores por sismo Nro. 103');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (104, 'Daño a equipos electrónicos por fluctuación de voltaje Nro. 104');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (105, 'Lesión por caída en las instalaciones comerciales aseguradas Nro. 105');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (106, 'Colisión de vehículo por detrás en intersección Nro. 106');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (107, 'Robo parcial de accesorios de vehículo en estacionamiento Nro. 107');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (108, 'Inundación de sótano por colapso de tubería de aguas lluvias Nro. 108');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (109, 'Rotura de cristales exteriores por vandalismo Nro. 109');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (110, 'Fractura de tobillo del asegurado en accidente doméstico Nro. 110');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (111, 'Fallecimiento natural del asegurado principal Nro. 111');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (112, 'Incendio parcial en área de cocina por cortocircuito Nro. 112');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (113, 'Daños por agua debido a filtración en el techo Nro. 113');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (114, 'Pérdida total del vehículo por colisión y vuelco Nro. 114');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (115, 'Robo con violencia de pertenencias personales en vía pública Nro. 115');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (116, 'Tratamiento de emergencia por intoxicación alimentaria Nro. 116');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (117, 'Cirugía programada de apendicitis Nro. 117');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (118, 'Daños estructurales menores por sismo Nro. 118');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (119, 'Daño a equipos electrónicos por fluctuación de voltaje Nro. 119');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (120, 'Lesión por caída en las instalaciones comerciales aseguradas Nro. 120');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (121, 'Colisión de vehículo por detrás en intersección Nro. 121');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (122, 'Robo parcial de accesorios de vehículo en estacionamiento Nro. 122');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (123, 'Inundación de sótano por colapso de tubería de aguas lluvias Nro. 123');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (124, 'Rotura de cristales exteriores por vandalismo Nro. 124');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (125, 'Fractura de tobillo del asegurado en accidente doméstico Nro. 125');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (126, 'Fallecimiento natural del asegurado principal Nro. 126');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (127, 'Incendio parcial en área de cocina por cortocircuito Nro. 127');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (128, 'Daños por agua debido a filtración en el techo Nro. 128');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (129, 'Pérdida total del vehículo por colisión y vuelco Nro. 129');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (130, 'Robo con violencia de pertenencias personales en vía pública Nro. 130');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (131, 'Tratamiento de emergencia por intoxicación alimentaria Nro. 131');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (132, 'Cirugía programada de apendicitis Nro. 132');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (133, 'Daños estructurales menores por sismo Nro. 133');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (134, 'Daño a equipos electrónicos por fluctuación de voltaje Nro. 134');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (135, 'Lesión por caída en las instalaciones comerciales aseguradas Nro. 135');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (136, 'Colisión de vehículo por detrás en intersección Nro. 136');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (137, 'Robo parcial de accesorios de vehículo en estacionamiento Nro. 137');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (138, 'Inundación de sótano por colapso de tubería de aguas lluvias Nro. 138');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (139, 'Rotura de cristales exteriores por vandalismo Nro. 139');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (140, 'Fractura de tobillo del asegurado en accidente doméstico Nro. 140');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (141, 'Fallecimiento natural del asegurado principal Nro. 141');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (142, 'Incendio parcial en área de cocina por cortocircuito Nro. 142');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (143, 'Daños por agua debido a filtración en el techo Nro. 143');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (144, 'Pérdida total del vehículo por colisión y vuelco Nro. 144');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (145, 'Robo con violencia de pertenencias personales en vía pública Nro. 145');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (146, 'Tratamiento de emergencia por intoxicación alimentaria Nro. 146');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (147, 'Cirugía programada de apendicitis Nro. 147');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (148, 'Daños estructurales menores por sismo Nro. 148');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (149, 'Daño a equipos electrónicos por fluctuación de voltaje Nro. 149');
INSERT INTO SINIESTRO (nro_siniestro, descripcion_siniestro) VALUES (150, 'Lesión por caída en las instalaciones comerciales aseguradas Nro. 150');
