-- PAIS Inserts
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (1, 'Japón');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (2, 'Indonesia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (3, 'India');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (4, 'China');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (5, 'Filipinas');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (6, 'Brasil');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (7, 'República de Corea');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (8, 'México');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (9, 'Egipto');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (10, 'Pakistán');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (11, 'Estados Unidos de América');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (12, 'Bangladesh');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (13, 'Tailandia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (14, 'Federación de Rusia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (15, 'República Democrática del Congo');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (16, 'Argentina');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (17, 'Nigeria');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (18, 'Türkiye');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (19, 'Viet Nam');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (20, 'Irán (República Islámica del)');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (21, 'Reino Unido de Gran Bretaña e Irlanda del Norte');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (22, 'Francia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (23, 'Perú');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (24, 'Colombia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (25, 'Angola');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (26, 'Malasia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (27, 'Iraq');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (28, 'República Unida de Tanzanía');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (29, 'Sudán');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (30, 'China, región administrativa especial de Hong Kong');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (31, 'Arabia Saudita');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (32, 'Chile');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (33, 'Myanmar');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (34, 'España');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (35, 'Singapur');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (36, 'Camerún');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (37, 'Etiopía');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (38, 'Canadá');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (39, 'Côte d’Ivoire');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (40, 'Kenya');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (41, 'Australia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (42, 'Afganistán');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (43, 'Alemania');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (44, 'Emiratos Árabes Unidos');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (45, 'Sudáfrica');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (46, 'República Dominicana');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (47, 'Malí');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (48, 'Jordania');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (49, 'Marruecos');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (50, 'Ghana');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (51, 'Taiwan');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (52, 'Bolivia (Estado Plurinacional de)');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (53, 'Ecuador');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (54, 'Hungría');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (55, 'Burkina Faso');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (56, 'Grecia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (57, 'Argelia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (58, 'Kuwait');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (59, 'Yemen');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (60, 'Uzbekistán');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (61, 'Ucrania');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (62, 'Haití');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (63, 'República Popular Democrática de Corea');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (64, 'Congo');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (65, 'Italia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (66, 'República Árabe Siria');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (67, 'Cuba');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (68, 'Zambia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (69, 'Líbano');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (70, 'Rumania');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (71, 'Sri Lanka');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (72, 'Azerbaiyán');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (73, 'Madagascar');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (74, 'Venezuela (República Bolivariana de)');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (75, 'Kazajstán');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (76, 'Austria');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (77, 'Togo');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (78, 'Zimbabwe');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (79, 'Camboya');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (80, 'Somalia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (81, 'Panamá');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (82, 'Polonia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (83, 'Belarús');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (84, 'Puerto Rico');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (85, 'Uruguay');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (86, 'Rwanda');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (87, 'Omán');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (88, 'Uganda');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (89, 'Guinea');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (90, 'El Salvador');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (91, 'Irlanda');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (92, 'Bulgaria');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (93, 'Níger');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (94, 'Países Bajos (Reino de los)');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (95, 'Nueva Zelandia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (96, 'Mauritania');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (97, 'Senegal');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (98, 'Chequia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (99, 'Dinamarca');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (100, 'Mongolia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (101, 'Portugal');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (102, 'Israel');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (103, 'Finlandia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (104, 'Serbia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (105, 'Bélgica');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (106, 'Honduras');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (107, 'Kirguistán');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (108, 'Jamaica');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (109, 'Qatar');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (110, 'Libia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (111, 'Burundi');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (112, 'Mozambique');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (113, 'Georgia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (114, 'Noruega');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (115, 'Túnez');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (116, 'Armenia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (117, 'Chad');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (118, 'Nicaragua');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (119, 'Turkmenistán');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (120, 'Liberia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (121, 'Suecia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (122, 'Guatemala');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (123, 'Malawi');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (124, 'Eritrea');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (125, 'Sierra Leona');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (126, 'República Democrática Popular Lao');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (127, 'Tayikistán');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (128, 'Gabón');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (129, 'República Centroafricana');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (130, 'Benin');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (131, 'Nepal');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (132, 'Lituania');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (133, 'Croacia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (134, 'Bahrein');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (135, 'China, región administrativa especial de Macao');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (136, 'Letonia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (137, 'Djibouti');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (138, 'Gaza Strip');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (139, 'República de Moldova');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (140, 'Albania');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (141, 'Sudán del Sur');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (142, 'Guinea-Bissau');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (143, 'Namibia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (144, 'Eslovaquia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (145, 'Malta');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (146, 'Paraguay');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (147, 'Estonia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (148, 'Suiza');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (149, 'Macedonia del Norte');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (150, 'Gambia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (151, 'Papua Nueva Guinea');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (152, 'Bosnia y Herzegovina');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (153, 'Lesotho');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (154, 'Costa Rica');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (155, 'Mauricio');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (156, 'Guinea Ecuatorial');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (157, 'Eslovenia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (158, 'Chipre');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (159, 'Botswana');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (160, 'Guyana');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (161, 'Bahamas');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (162, 'Kosovo');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (163, 'Suriname');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (164, 'Timor-Leste');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (165, 'West Bank');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (166, 'Fiji');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (167, 'Montenegro');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (168, 'Cabo Verde');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (169, 'Reunión');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (170, 'Curazao');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (171, 'Islandia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (172, 'Luxemburgo');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (173, 'Maldivas');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (174, 'Guam');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (175, 'Eswatini');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (176, 'Bhután');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (177, 'Trinidad y Tabago');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (178, 'Barbados');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (179, 'Nueva Caledonia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (180, 'Comoras');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (181, 'Islas Salomón');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (182, 'Martinica');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (183, 'Mayotte');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (184, 'Kiribati');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (185, 'Santo Tomé y Príncipe');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (186, 'Belice');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (187, 'Guayana Francesa');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (188, 'Brunei Darussalam');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (189, 'Vanuatu');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (190, 'Mónaco');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (191, 'Samoa');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (192, 'Jersey');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (193, 'Gibraltar');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (194, 'Granada');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (195, 'Islas Marshall');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (196, 'Aruba');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (197, 'Islas Caimán');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (198, 'Isla de Man');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (199, 'Polinesia Francesa');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (200, 'Seychelles');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (201, 'San Vicente y las Granadinas');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (202, 'Tonga');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (203, 'Andorra');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (204, 'Santa Lucía');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (205, 'Antigua y Barbuda');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (206, 'Guernsey');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (207, 'Groenlandia');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (208, 'Dominica');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (209, 'Guadalupe');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (210, 'Islas Feroe');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (211, 'Micronesia (Estados Federados de)');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (212, 'Saint Kitts y Nevis');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (213, 'Islas Vírgenes Británicas');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (214, 'Samoa Americana');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (215, 'Bonaire, San Eustaquio y Saba');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (216, 'San Marino');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (217, 'San Barthélemy');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (218, 'Palau');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (219, 'Liechtenstein');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (220, 'Tuvalu');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (221, 'San Martín (parte francesa)');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (222, 'San Pedro y Miquelón');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (223, 'Islas Cook');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (224, 'Islas Turcas y Caicos');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (225, 'Islas Marianas Septentrionales');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (226, 'Svalbard');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (227, 'Islas Malvinas (Falkland)');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (228, 'Santa Elena');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (229, 'Isla Christmas');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (230, 'San Martín (parte Holandesa)');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (231, 'Islas Wallis y Futuna');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (232, 'Anguila');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (233, 'Bermuda');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (234, 'Santa Sede');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (235, 'Nauru');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (236, 'Niue');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (237, 'Montserrat');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (238, 'Isla Norfolk');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (239, 'Pitcairn');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (240, 'Georgia del Sur y las Islas Sandwich del Sur');
INSERT INTO PAIS (cod_pais, nb_pais) VALUES (241, 'Islas Vírgenes de los Estados Unidos');
