-- SUCURSAL Inserts
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (1, 'Sucursal Tokyo', 1);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (2, 'Sucursal Jakarta', 2);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (3, 'Sucursal Delhi', 3);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (4, 'Sucursal Chongqing', 4);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (5, 'Sucursal Guangzhou', 5);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (6, 'Sucursal Mumbai', 6);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (7, 'Sucursal Manila', 7);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (8, 'Sucursal Shanghai', 8);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (9, 'Sucursal São Paulo', 9);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (10, 'Sucursal Seoul', 10);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (11, 'Sucursal Beijing', 11);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (12, 'Sucursal Mexico City', 12);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (13, 'Sucursal Kolkāta', 13);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (14, 'Sucursal Chengdu', 14);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (15, 'Sucursal Cairo', 15);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (16, 'Sucursal Karachi', 16);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (17, 'Sucursal New York', 17);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (18, 'Sucursal Dhaka', 18);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (19, 'Sucursal Bangkok', 19);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (20, 'Sucursal Shenzhen', 20);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (21, 'Sucursal Moscow', 21);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (22, 'Sucursal Kinshasa', 22);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (23, 'Sucursal Buenos Aires', 23);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (24, 'Sucursal Lagos', 24);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (25, 'Sucursal Istanbul', 25);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (26, 'Sucursal Ho Chi Minh City', 26);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (27, 'Sucursal Ōsaka', 27);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (28, 'Sucursal Tehran', 28);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (29, 'Sucursal Tianjin', 29);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (30, 'Sucursal Lahore', 30);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (31, 'Sucursal Suzhou', 31);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (32, 'Sucursal Rio de Janeiro', 32);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (33, 'Sucursal Wuhan', 33);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (34, 'Sucursal Chennai', 34);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (35, 'Sucursal Xi’an', 35);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (36, 'Sucursal Los Angeles', 36);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (37, 'Sucursal Hangzhou', 37);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (38, 'Sucursal Baoding', 38);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (39, 'Sucursal London', 39);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (40, 'Sucursal Paris', 40);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (41, 'Sucursal Linyi', 41);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (42, 'Sucursal Dongguan', 42);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (43, 'Sucursal Harbin', 43);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (44, 'Sucursal Hyderābād', 44);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (45, 'Sucursal Lima', 45);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (46, 'Sucursal Bogotá', 46);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (47, 'Sucursal Qingdao', 47);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (48, 'Sucursal Nanyang', 48);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (49, 'Sucursal Foshan', 49);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (50, 'Sucursal Nanjing', 50);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (51, 'Sucursal Jinan', 51);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (52, 'Sucursal Nagoya', 52);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (53, 'Sucursal Tongshan', 53);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (54, 'Sucursal Luanda', 54);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (55, 'Sucursal Zhoukou', 55);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (56, 'Sucursal Ganzhou', 56);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (57, 'Sucursal Kuala Lumpur', 57);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (58, 'Sucursal Heze', 58);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (59, 'Sucursal Quanzhou', 59);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (60, 'Sucursal Hanoi', 60);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (61, 'Sucursal Chicago', 61);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (62, 'Sucursal Bangalore', 62);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (63, 'Sucursal Jining', 63);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (64, 'Sucursal Shenyang', 64);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (65, 'Sucursal Pune', 65);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (66, 'Sucursal Fuyang', 66);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (67, 'Sucursal Baghdad', 67);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (68, 'Sucursal Ahmedabad', 68);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (69, 'Sucursal Dar es Salaam', 69);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (70, 'Sucursal Khartoum', 70);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (71, 'Sucursal Shangqiu', 71);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (72, 'Sucursal Dalian', 72);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (73, 'Sucursal Hong Kong', 73);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (74, 'Sucursal Cangzhou', 74);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (75, 'Sucursal Riyadh', 75);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (76, 'Sucursal Bandung', 76);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (77, 'Sucursal Santiago', 77);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (78, 'Sucursal Xingtai', 78);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (79, 'Sucursal Zhumadian', 79);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (80, 'Sucursal Zhanjiang', 80);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (81, 'Sucursal Bijie', 81);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (82, 'Sucursal Rangoon', 82);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (83, 'Sucursal Yancheng', 83);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (84, 'Sucursal Hengyang', 84);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (85, 'Sucursal Zunyi', 85);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (86, 'Sucursal Shaoyang', 86);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (87, 'Sucursal Surabaya', 87);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (88, 'Sucursal Sūrat', 88);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (89, 'Sucursal Shangrao', 89);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (90, 'Sucursal Miami', 90);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (91, 'Sucursal Huanggang', 91);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (92, 'Sucursal Maoming', 92);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (93, 'Sucursal Nangandao', 93);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (94, 'Sucursal Xinyang', 94);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (95, 'Sucursal Houston', 95);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (96, 'Sucursal Madrid', 96);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (97, 'Sucursal Singapore', 97);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (98, 'Sucursal Dallas', 98);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (99, 'Sucursal Prayagraj', 99);
INSERT INTO SUCURSAL (cod_sucursal, nb_sucursal, cod_ciudad) VALUES (100, 'Sucursal Liaocheng', 100);
