-- CONTRATO Inserts
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (1, 'Póliza de Seguro de Vida Familiar Nro. 1');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (2, 'Contrato de Seguro Médico Individual Nro. 2');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (3, 'Póliza de Responsabilidad Civil General Nro. 3');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (4, 'Contrato de Cobertura contra Todo Riesgo Nro. 4');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (5, 'Póliza de Seguro de Propiedad Comercial Nro. 5');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (6, 'Contrato de Seguro de Viajes Internacionales Nro. 6');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (7, 'Póliza de Seguro de Flota de Vehículos Nro. 7');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (8, 'Contrato de Seguro contra Incendios y Desastres Nro. 8');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (9, 'Póliza de Responsabilidad Profesional Especializada Nro. 9');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (10, 'Contrato de Seguro de Cobertura Amplia Nro. 10');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (11, 'Póliza de Seguro de Vida Familiar Nro. 11');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (12, 'Contrato de Seguro Médico Individual Nro. 12');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (13, 'Póliza de Responsabilidad Civil General Nro. 13');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (14, 'Contrato de Cobertura contra Todo Riesgo Nro. 14');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (15, 'Póliza de Seguro de Propiedad Comercial Nro. 15');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (16, 'Contrato de Seguro de Viajes Internacionales Nro. 16');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (17, 'Póliza de Seguro de Flota de Vehículos Nro. 17');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (18, 'Contrato de Seguro contra Incendios y Desastres Nro. 18');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (19, 'Póliza de Responsabilidad Profesional Especializada Nro. 19');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (20, 'Contrato de Seguro de Cobertura Amplia Nro. 20');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (21, 'Póliza de Seguro de Vida Familiar Nro. 21');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (22, 'Contrato de Seguro Médico Individual Nro. 22');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (23, 'Póliza de Responsabilidad Civil General Nro. 23');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (24, 'Contrato de Cobertura contra Todo Riesgo Nro. 24');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (25, 'Póliza de Seguro de Propiedad Comercial Nro. 25');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (26, 'Contrato de Seguro de Viajes Internacionales Nro. 26');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (27, 'Póliza de Seguro de Flota de Vehículos Nro. 27');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (28, 'Contrato de Seguro contra Incendios y Desastres Nro. 28');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (29, 'Póliza de Responsabilidad Profesional Especializada Nro. 29');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (30, 'Contrato de Seguro de Cobertura Amplia Nro. 30');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (31, 'Póliza de Seguro de Vida Familiar Nro. 31');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (32, 'Contrato de Seguro Médico Individual Nro. 32');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (33, 'Póliza de Responsabilidad Civil General Nro. 33');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (34, 'Contrato de Cobertura contra Todo Riesgo Nro. 34');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (35, 'Póliza de Seguro de Propiedad Comercial Nro. 35');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (36, 'Contrato de Seguro de Viajes Internacionales Nro. 36');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (37, 'Póliza de Seguro de Flota de Vehículos Nro. 37');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (38, 'Contrato de Seguro contra Incendios y Desastres Nro. 38');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (39, 'Póliza de Responsabilidad Profesional Especializada Nro. 39');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (40, 'Contrato de Seguro de Cobertura Amplia Nro. 40');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (41, 'Póliza de Seguro de Vida Familiar Nro. 41');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (42, 'Contrato de Seguro Médico Individual Nro. 42');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (43, 'Póliza de Responsabilidad Civil General Nro. 43');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (44, 'Contrato de Cobertura contra Todo Riesgo Nro. 44');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (45, 'Póliza de Seguro de Propiedad Comercial Nro. 45');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (46, 'Contrato de Seguro de Viajes Internacionales Nro. 46');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (47, 'Póliza de Seguro de Flota de Vehículos Nro. 47');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (48, 'Contrato de Seguro contra Incendios y Desastres Nro. 48');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (49, 'Póliza de Responsabilidad Profesional Especializada Nro. 49');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (50, 'Contrato de Seguro de Cobertura Amplia Nro. 50');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (51, 'Póliza de Seguro de Vida Familiar Nro. 51');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (52, 'Contrato de Seguro Médico Individual Nro. 52');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (53, 'Póliza de Responsabilidad Civil General Nro. 53');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (54, 'Contrato de Cobertura contra Todo Riesgo Nro. 54');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (55, 'Póliza de Seguro de Propiedad Comercial Nro. 55');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (56, 'Contrato de Seguro de Viajes Internacionales Nro. 56');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (57, 'Póliza de Seguro de Flota de Vehículos Nro. 57');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (58, 'Contrato de Seguro contra Incendios y Desastres Nro. 58');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (59, 'Póliza de Responsabilidad Profesional Especializada Nro. 59');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (60, 'Contrato de Seguro de Cobertura Amplia Nro. 60');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (61, 'Póliza de Seguro de Vida Familiar Nro. 61');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (62, 'Contrato de Seguro Médico Individual Nro. 62');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (63, 'Póliza de Responsabilidad Civil General Nro. 63');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (64, 'Contrato de Cobertura contra Todo Riesgo Nro. 64');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (65, 'Póliza de Seguro de Propiedad Comercial Nro. 65');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (66, 'Contrato de Seguro de Viajes Internacionales Nro. 66');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (67, 'Póliza de Seguro de Flota de Vehículos Nro. 67');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (68, 'Contrato de Seguro contra Incendios y Desastres Nro. 68');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (69, 'Póliza de Responsabilidad Profesional Especializada Nro. 69');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (70, 'Contrato de Seguro de Cobertura Amplia Nro. 70');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (71, 'Póliza de Seguro de Vida Familiar Nro. 71');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (72, 'Contrato de Seguro Médico Individual Nro. 72');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (73, 'Póliza de Responsabilidad Civil General Nro. 73');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (74, 'Contrato de Cobertura contra Todo Riesgo Nro. 74');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (75, 'Póliza de Seguro de Propiedad Comercial Nro. 75');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (76, 'Contrato de Seguro de Viajes Internacionales Nro. 76');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (77, 'Póliza de Seguro de Flota de Vehículos Nro. 77');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (78, 'Contrato de Seguro contra Incendios y Desastres Nro. 78');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (79, 'Póliza de Responsabilidad Profesional Especializada Nro. 79');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (80, 'Contrato de Seguro de Cobertura Amplia Nro. 80');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (81, 'Póliza de Seguro de Vida Familiar Nro. 81');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (82, 'Contrato de Seguro Médico Individual Nro. 82');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (83, 'Póliza de Responsabilidad Civil General Nro. 83');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (84, 'Contrato de Cobertura contra Todo Riesgo Nro. 84');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (85, 'Póliza de Seguro de Propiedad Comercial Nro. 85');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (86, 'Contrato de Seguro de Viajes Internacionales Nro. 86');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (87, 'Póliza de Seguro de Flota de Vehículos Nro. 87');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (88, 'Contrato de Seguro contra Incendios y Desastres Nro. 88');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (89, 'Póliza de Responsabilidad Profesional Especializada Nro. 89');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (90, 'Contrato de Seguro de Cobertura Amplia Nro. 90');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (91, 'Póliza de Seguro de Vida Familiar Nro. 91');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (92, 'Contrato de Seguro Médico Individual Nro. 92');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (93, 'Póliza de Responsabilidad Civil General Nro. 93');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (94, 'Contrato de Cobertura contra Todo Riesgo Nro. 94');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (95, 'Póliza de Seguro de Propiedad Comercial Nro. 95');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (96, 'Contrato de Seguro de Viajes Internacionales Nro. 96');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (97, 'Póliza de Seguro de Flota de Vehículos Nro. 97');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (98, 'Contrato de Seguro contra Incendios y Desastres Nro. 98');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (99, 'Póliza de Responsabilidad Profesional Especializada Nro. 99');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (100, 'Contrato de Seguro de Cobertura Amplia Nro. 100');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (101, 'Póliza de Seguro de Vida Familiar Nro. 101');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (102, 'Contrato de Seguro Médico Individual Nro. 102');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (103, 'Póliza de Responsabilidad Civil General Nro. 103');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (104, 'Contrato de Cobertura contra Todo Riesgo Nro. 104');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (105, 'Póliza de Seguro de Propiedad Comercial Nro. 105');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (106, 'Contrato de Seguro de Viajes Internacionales Nro. 106');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (107, 'Póliza de Seguro de Flota de Vehículos Nro. 107');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (108, 'Contrato de Seguro contra Incendios y Desastres Nro. 108');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (109, 'Póliza de Responsabilidad Profesional Especializada Nro. 109');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (110, 'Contrato de Seguro de Cobertura Amplia Nro. 110');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (111, 'Póliza de Seguro de Vida Familiar Nro. 111');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (112, 'Contrato de Seguro Médico Individual Nro. 112');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (113, 'Póliza de Responsabilidad Civil General Nro. 113');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (114, 'Contrato de Cobertura contra Todo Riesgo Nro. 114');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (115, 'Póliza de Seguro de Propiedad Comercial Nro. 115');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (116, 'Contrato de Seguro de Viajes Internacionales Nro. 116');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (117, 'Póliza de Seguro de Flota de Vehículos Nro. 117');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (118, 'Contrato de Seguro contra Incendios y Desastres Nro. 118');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (119, 'Póliza de Responsabilidad Profesional Especializada Nro. 119');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (120, 'Contrato de Seguro de Cobertura Amplia Nro. 120');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (121, 'Póliza de Seguro de Vida Familiar Nro. 121');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (122, 'Contrato de Seguro Médico Individual Nro. 122');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (123, 'Póliza de Responsabilidad Civil General Nro. 123');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (124, 'Contrato de Cobertura contra Todo Riesgo Nro. 124');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (125, 'Póliza de Seguro de Propiedad Comercial Nro. 125');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (126, 'Contrato de Seguro de Viajes Internacionales Nro. 126');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (127, 'Póliza de Seguro de Flota de Vehículos Nro. 127');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (128, 'Contrato de Seguro contra Incendios y Desastres Nro. 128');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (129, 'Póliza de Responsabilidad Profesional Especializada Nro. 129');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (130, 'Contrato de Seguro de Cobertura Amplia Nro. 130');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (131, 'Póliza de Seguro de Vida Familiar Nro. 131');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (132, 'Contrato de Seguro Médico Individual Nro. 132');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (133, 'Póliza de Responsabilidad Civil General Nro. 133');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (134, 'Contrato de Cobertura contra Todo Riesgo Nro. 134');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (135, 'Póliza de Seguro de Propiedad Comercial Nro. 135');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (136, 'Contrato de Seguro de Viajes Internacionales Nro. 136');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (137, 'Póliza de Seguro de Flota de Vehículos Nro. 137');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (138, 'Contrato de Seguro contra Incendios y Desastres Nro. 138');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (139, 'Póliza de Responsabilidad Profesional Especializada Nro. 139');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (140, 'Contrato de Seguro de Cobertura Amplia Nro. 140');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (141, 'Póliza de Seguro de Vida Familiar Nro. 141');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (142, 'Contrato de Seguro Médico Individual Nro. 142');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (143, 'Póliza de Responsabilidad Civil General Nro. 143');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (144, 'Contrato de Cobertura contra Todo Riesgo Nro. 144');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (145, 'Póliza de Seguro de Propiedad Comercial Nro. 145');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (146, 'Contrato de Seguro de Viajes Internacionales Nro. 146');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (147, 'Póliza de Seguro de Flota de Vehículos Nro. 147');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (148, 'Contrato de Seguro contra Incendios y Desastres Nro. 148');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (149, 'Póliza de Responsabilidad Profesional Especializada Nro. 149');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (150, 'Contrato de Seguro de Cobertura Amplia Nro. 150');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (151, 'Póliza de Seguro de Vida Familiar Nro. 151');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (152, 'Contrato de Seguro Médico Individual Nro. 152');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (153, 'Póliza de Responsabilidad Civil General Nro. 153');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (154, 'Contrato de Cobertura contra Todo Riesgo Nro. 154');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (155, 'Póliza de Seguro de Propiedad Comercial Nro. 155');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (156, 'Contrato de Seguro de Viajes Internacionales Nro. 156');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (157, 'Póliza de Seguro de Flota de Vehículos Nro. 157');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (158, 'Contrato de Seguro contra Incendios y Desastres Nro. 158');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (159, 'Póliza de Responsabilidad Profesional Especializada Nro. 159');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (160, 'Contrato de Seguro de Cobertura Amplia Nro. 160');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (161, 'Póliza de Seguro de Vida Familiar Nro. 161');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (162, 'Contrato de Seguro Médico Individual Nro. 162');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (163, 'Póliza de Responsabilidad Civil General Nro. 163');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (164, 'Contrato de Cobertura contra Todo Riesgo Nro. 164');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (165, 'Póliza de Seguro de Propiedad Comercial Nro. 165');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (166, 'Contrato de Seguro de Viajes Internacionales Nro. 166');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (167, 'Póliza de Seguro de Flota de Vehículos Nro. 167');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (168, 'Contrato de Seguro contra Incendios y Desastres Nro. 168');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (169, 'Póliza de Responsabilidad Profesional Especializada Nro. 169');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (170, 'Contrato de Seguro de Cobertura Amplia Nro. 170');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (171, 'Póliza de Seguro de Vida Familiar Nro. 171');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (172, 'Contrato de Seguro Médico Individual Nro. 172');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (173, 'Póliza de Responsabilidad Civil General Nro. 173');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (174, 'Contrato de Cobertura contra Todo Riesgo Nro. 174');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (175, 'Póliza de Seguro de Propiedad Comercial Nro. 175');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (176, 'Contrato de Seguro de Viajes Internacionales Nro. 176');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (177, 'Póliza de Seguro de Flota de Vehículos Nro. 177');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (178, 'Contrato de Seguro contra Incendios y Desastres Nro. 178');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (179, 'Póliza de Responsabilidad Profesional Especializada Nro. 179');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (180, 'Contrato de Seguro de Cobertura Amplia Nro. 180');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (181, 'Póliza de Seguro de Vida Familiar Nro. 181');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (182, 'Contrato de Seguro Médico Individual Nro. 182');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (183, 'Póliza de Responsabilidad Civil General Nro. 183');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (184, 'Contrato de Cobertura contra Todo Riesgo Nro. 184');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (185, 'Póliza de Seguro de Propiedad Comercial Nro. 185');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (186, 'Contrato de Seguro de Viajes Internacionales Nro. 186');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (187, 'Póliza de Seguro de Flota de Vehículos Nro. 187');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (188, 'Contrato de Seguro contra Incendios y Desastres Nro. 188');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (189, 'Póliza de Responsabilidad Profesional Especializada Nro. 189');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (190, 'Contrato de Seguro de Cobertura Amplia Nro. 190');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (191, 'Póliza de Seguro de Vida Familiar Nro. 191');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (192, 'Contrato de Seguro Médico Individual Nro. 192');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (193, 'Póliza de Responsabilidad Civil General Nro. 193');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (194, 'Contrato de Cobertura contra Todo Riesgo Nro. 194');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (195, 'Póliza de Seguro de Propiedad Comercial Nro. 195');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (196, 'Contrato de Seguro de Viajes Internacionales Nro. 196');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (197, 'Póliza de Seguro de Flota de Vehículos Nro. 197');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (198, 'Contrato de Seguro contra Incendios y Desastres Nro. 198');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (199, 'Póliza de Responsabilidad Profesional Especializada Nro. 199');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (200, 'Contrato de Seguro de Cobertura Amplia Nro. 200');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (201, 'Póliza de Seguro de Vida Familiar Nro. 201');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (202, 'Contrato de Seguro Médico Individual Nro. 202');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (203, 'Póliza de Responsabilidad Civil General Nro. 203');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (204, 'Contrato de Cobertura contra Todo Riesgo Nro. 204');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (205, 'Póliza de Seguro de Propiedad Comercial Nro. 205');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (206, 'Contrato de Seguro de Viajes Internacionales Nro. 206');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (207, 'Póliza de Seguro de Flota de Vehículos Nro. 207');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (208, 'Contrato de Seguro contra Incendios y Desastres Nro. 208');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (209, 'Póliza de Responsabilidad Profesional Especializada Nro. 209');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (210, 'Contrato de Seguro de Cobertura Amplia Nro. 210');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (211, 'Póliza de Seguro de Vida Familiar Nro. 211');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (212, 'Contrato de Seguro Médico Individual Nro. 212');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (213, 'Póliza de Responsabilidad Civil General Nro. 213');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (214, 'Contrato de Cobertura contra Todo Riesgo Nro. 214');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (215, 'Póliza de Seguro de Propiedad Comercial Nro. 215');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (216, 'Contrato de Seguro de Viajes Internacionales Nro. 216');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (217, 'Póliza de Seguro de Flota de Vehículos Nro. 217');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (218, 'Contrato de Seguro contra Incendios y Desastres Nro. 218');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (219, 'Póliza de Responsabilidad Profesional Especializada Nro. 219');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (220, 'Contrato de Seguro de Cobertura Amplia Nro. 220');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (221, 'Póliza de Seguro de Vida Familiar Nro. 221');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (222, 'Contrato de Seguro Médico Individual Nro. 222');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (223, 'Póliza de Responsabilidad Civil General Nro. 223');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (224, 'Contrato de Cobertura contra Todo Riesgo Nro. 224');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (225, 'Póliza de Seguro de Propiedad Comercial Nro. 225');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (226, 'Contrato de Seguro de Viajes Internacionales Nro. 226');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (227, 'Póliza de Seguro de Flota de Vehículos Nro. 227');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (228, 'Contrato de Seguro contra Incendios y Desastres Nro. 228');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (229, 'Póliza de Responsabilidad Profesional Especializada Nro. 229');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (230, 'Contrato de Seguro de Cobertura Amplia Nro. 230');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (231, 'Póliza de Seguro de Vida Familiar Nro. 231');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (232, 'Contrato de Seguro Médico Individual Nro. 232');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (233, 'Póliza de Responsabilidad Civil General Nro. 233');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (234, 'Contrato de Cobertura contra Todo Riesgo Nro. 234');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (235, 'Póliza de Seguro de Propiedad Comercial Nro. 235');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (236, 'Contrato de Seguro de Viajes Internacionales Nro. 236');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (237, 'Póliza de Seguro de Flota de Vehículos Nro. 237');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (238, 'Contrato de Seguro contra Incendios y Desastres Nro. 238');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (239, 'Póliza de Responsabilidad Profesional Especializada Nro. 239');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (240, 'Contrato de Seguro de Cobertura Amplia Nro. 240');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (241, 'Póliza de Seguro de Vida Familiar Nro. 241');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (242, 'Contrato de Seguro Médico Individual Nro. 242');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (243, 'Póliza de Responsabilidad Civil General Nro. 243');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (244, 'Contrato de Cobertura contra Todo Riesgo Nro. 244');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (245, 'Póliza de Seguro de Propiedad Comercial Nro. 245');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (246, 'Contrato de Seguro de Viajes Internacionales Nro. 246');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (247, 'Póliza de Seguro de Flota de Vehículos Nro. 247');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (248, 'Contrato de Seguro contra Incendios y Desastres Nro. 248');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (249, 'Póliza de Responsabilidad Profesional Especializada Nro. 249');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (250, 'Contrato de Seguro de Cobertura Amplia Nro. 250');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (251, 'Póliza de Seguro de Vida Familiar Nro. 251');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (252, 'Contrato de Seguro Médico Individual Nro. 252');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (253, 'Póliza de Responsabilidad Civil General Nro. 253');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (254, 'Contrato de Cobertura contra Todo Riesgo Nro. 254');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (255, 'Póliza de Seguro de Propiedad Comercial Nro. 255');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (256, 'Contrato de Seguro de Viajes Internacionales Nro. 256');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (257, 'Póliza de Seguro de Flota de Vehículos Nro. 257');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (258, 'Contrato de Seguro contra Incendios y Desastres Nro. 258');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (259, 'Póliza de Responsabilidad Profesional Especializada Nro. 259');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (260, 'Contrato de Seguro de Cobertura Amplia Nro. 260');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (261, 'Póliza de Seguro de Vida Familiar Nro. 261');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (262, 'Contrato de Seguro Médico Individual Nro. 262');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (263, 'Póliza de Responsabilidad Civil General Nro. 263');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (264, 'Contrato de Cobertura contra Todo Riesgo Nro. 264');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (265, 'Póliza de Seguro de Propiedad Comercial Nro. 265');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (266, 'Contrato de Seguro de Viajes Internacionales Nro. 266');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (267, 'Póliza de Seguro de Flota de Vehículos Nro. 267');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (268, 'Contrato de Seguro contra Incendios y Desastres Nro. 268');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (269, 'Póliza de Responsabilidad Profesional Especializada Nro. 269');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (270, 'Contrato de Seguro de Cobertura Amplia Nro. 270');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (271, 'Póliza de Seguro de Vida Familiar Nro. 271');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (272, 'Contrato de Seguro Médico Individual Nro. 272');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (273, 'Póliza de Responsabilidad Civil General Nro. 273');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (274, 'Contrato de Cobertura contra Todo Riesgo Nro. 274');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (275, 'Póliza de Seguro de Propiedad Comercial Nro. 275');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (276, 'Contrato de Seguro de Viajes Internacionales Nro. 276');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (277, 'Póliza de Seguro de Flota de Vehículos Nro. 277');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (278, 'Contrato de Seguro contra Incendios y Desastres Nro. 278');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (279, 'Póliza de Responsabilidad Profesional Especializada Nro. 279');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (280, 'Contrato de Seguro de Cobertura Amplia Nro. 280');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (281, 'Póliza de Seguro de Vida Familiar Nro. 281');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (282, 'Contrato de Seguro Médico Individual Nro. 282');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (283, 'Póliza de Responsabilidad Civil General Nro. 283');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (284, 'Contrato de Cobertura contra Todo Riesgo Nro. 284');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (285, 'Póliza de Seguro de Propiedad Comercial Nro. 285');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (286, 'Contrato de Seguro de Viajes Internacionales Nro. 286');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (287, 'Póliza de Seguro de Flota de Vehículos Nro. 287');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (288, 'Contrato de Seguro contra Incendios y Desastres Nro. 288');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (289, 'Póliza de Responsabilidad Profesional Especializada Nro. 289');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (290, 'Contrato de Seguro de Cobertura Amplia Nro. 290');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (291, 'Póliza de Seguro de Vida Familiar Nro. 291');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (292, 'Contrato de Seguro Médico Individual Nro. 292');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (293, 'Póliza de Responsabilidad Civil General Nro. 293');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (294, 'Contrato de Cobertura contra Todo Riesgo Nro. 294');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (295, 'Póliza de Seguro de Propiedad Comercial Nro. 295');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (296, 'Contrato de Seguro de Viajes Internacionales Nro. 296');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (297, 'Póliza de Seguro de Flota de Vehículos Nro. 297');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (298, 'Contrato de Seguro contra Incendios y Desastres Nro. 298');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (299, 'Póliza de Responsabilidad Profesional Especializada Nro. 299');
INSERT INTO CONTRATO (nro_contrato, descrip_contrato) VALUES (300, 'Contrato de Seguro de Cobertura Amplia Nro. 300');
