-- creación del esquema solicitado (sustituir XX por la cédula correspondiente)
CREATE SCHEMA SEGURO_DW_GXX;
SET search_path TO SEGURO_DW_GXX;

-- dimensiones

CREATE TABLE DIM_TIEMPO (
    SK_DIM_TIEMPO INTEGER PRIMARY KEY,
    COD_ANNIO INTEGER,
    COD_MES INTEGER,
    COD_DIA INTEGER,
    DESC_MES VARCHAR(20),
    DESC_TRIMESTRE VARCHAR(10),
    DESC_SEMESTRE VARCHAR(10),
    FECHA_COMPLETA DATE
);

CREATE TABLE DIM_CLIENTE (
    SK_DIM_CLIENTE INTEGER PRIMARY KEY,
    COD_CLIENTE VARCHAR(50),
    NB_CLIENTE VARCHAR(100),
    CI_RIF VARCHAR(20),
    TELEFONO VARCHAR(50),
    DIRECCION VARCHAR(255),
    SEXO CHAR(1),
    EMAIL VARCHAR(100)
);

CREATE TABLE DIM_PRODUCTO (
    SK_DIM_PRODUCTO INTEGER PRIMARY KEY,
    COD_PRODUCTO VARCHAR(50),
    NB_PRODUCTO VARCHAR(100),
    DESCRIP_PRODUCTO VARCHAR(255),
    COD_TIPO_PRODUCTO VARCHAR(50),
    NB_TIPO_PRODUCTO VARCHAR(100),
    CALIFICACION INTEGER
);

CREATE TABLE DIM_CONTRATO (
    SK_DIM_CONTRATO INTEGER PRIMARY KEY,
    NRO_CONTRATO VARCHAR(50),
    DESCRIP_CONTRATO VARCHAR(255)
);

CREATE TABLE DIM_SUCURSAL (
    SK_DIM_SUCURSAL INTEGER PRIMARY KEY,
    COD_SUCURSAL VARCHAR(50),
    NB_SUCURSAL VARCHAR(100),
    COD_CIUDAD VARCHAR(50),
    NB_CIUDAD VARCHAR(100),
    COD_PAIS VARCHAR(50),
    NB_PAIS VARCHAR(100)
);

CREATE TABLE DIM_ESTADO_CONTRATO (
    SK_DIM_ESTADO INTEGER PRIMARY KEY,
    COD_ESTADO CHAR(2),
    DESCRIP_ESTADO VARCHAR(50)
);

CREATE TABLE DIM_EVALUACION_SERVICIO (
    SK_DIM_EVALUACION INTEGER PRIMARY KEY,
    COD_EVALUACION VARCHAR(50),
    NB_DESCRIP VARCHAR(50)
);

CREATE TABLE DIM_SINIESTRO (
    SK_DIM_SINIESTRO INTEGER PRIMARY KEY,
    NRO_SINIESTRO VARCHAR(50),
    DESCRIP_SINIESTRO VARCHAR(255)
);

-- tablas de hechos

CREATE TABLE FACT_REGISTRO_CONTRATO (
    SK_DIM_TIEMPO_FECHA_INICIO INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    SK_DIM_TIEMPO_FECHA_FIN INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    SK_DIM_CLIENTE INTEGER REFERENCES DIM_CLIENTE(SK_DIM_CLIENTE),
    SK_DIM_CONTRATO INTEGER REFERENCES DIM_CONTRATO(SK_DIM_CONTRATO),
    SK_DIM_PRODUCTO INTEGER REFERENCES DIM_PRODUCTO(SK_DIM_PRODUCTO),
    SK_DIM_ESTADO_CONTRATO INTEGER REFERENCES DIM_ESTADO_CONTRATO(SK_DIM_ESTADO),
    MONTO REAL,
    CANTIDAD INTEGER,
    CANTIDAD_CLIENTE INTEGER,
    CANTIDAD_PRODUCTO INTEGER,
    CANTIDAD_CONTRATO INTEGER
);

CREATE TABLE FACT_REGISTRO_SINIESTRO (
    SK_FECHA_SINIESTRO INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    SK_FECHA_RESPUESTA INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    SK_DIM_CLIENTE INTEGER REFERENCES DIM_CLIENTE(SK_DIM_CLIENTE),
    SK_DIM_CONTRATO INTEGER REFERENCES DIM_CONTRATO(SK_DIM_CONTRATO),
    SK_DIM_SUCURSAL INTEGER REFERENCES DIM_SUCURSAL(SK_DIM_SUCURSAL),
    SK_DIM_PRODUCTO INTEGER REFERENCES DIM_PRODUCTO(SK_DIM_PRODUCTO),
    SK_DIM_SINIESTRO INTEGER REFERENCES DIM_SINIESTRO(SK_DIM_SINIESTRO),
    CANTIDAD INTEGER,
    MONTO_RECONOCIDO REAL,
    MONTO_SOLICITADO REAL,
    ID_RECHAZO CHAR(2)
);

CREATE TABLE FACT_EVALUACION_SERVICIO (
    SK_DIM_CLIENTE INTEGER REFERENCES DIM_CLIENTE(SK_DIM_CLIENTE),
    SK_DIM_PRODUCTO INTEGER REFERENCES DIM_PRODUCTO(SK_DIM_PRODUCTO),
    SK_DIM_EVALUACION_SERVICIO INTEGER REFERENCES DIM_EVALUACION_SERVICIO(SK_DIM_EVALUACION),
    CANTIDAD INTEGER,
    RECOMIENDA_AMIGO REAL
);

CREATE TABLE FACT_METAS (
    SK_DIM_FECHA_INICIO_META INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    SK_DIM_FECHA_FIN_META INTEGER REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    SK_DIM_CLIENTE INTEGER REFERENCES DIM_CLIENTE(SK_DIM_CLIENTE),
    SK_DIM_PRODUCTO INTEGER REFERENCES DIM_PRODUCTO(SK_DIM_PRODUCTO),
    SK_DIM_CONTRATO INTEGER REFERENCES DIM_CONTRATO(SK_DIM_CONTRATO),
    MONTO_META_INGRESO REAL,
    META_RENOVACION INTEGER,
    META_ASEGURADOS INTEGER
);