-- Script to delete all data from tables respecting referential integrity (child tables first)

-- 1. REGISTRO_SINIESTRO (References SINIESTRO and REGISTRO_CONTRATO)
DELETE FROM REGISTRO_SINIESTRO;

-- 2. SINIESTRO
DELETE FROM SINIESTRO;

-- 3. METAS (References CLIENTE, PRODUCTO and CONTRATO)
DELETE FROM METAS;

-- 4. REGISTRO_CONTRATO (References CONTRATO, PRODUCTO and CLIENTE)
DELETE FROM REGISTRO_CONTRATO;

-- 5. CONTRATO
DELETE FROM CONTRATO;

-- 6. RECOMIENDA (References CLIENTE, EVALUACION_SERVICIO and PRODUCTO)
DELETE FROM RECOMIENDA;

-- 7. EVALUACION_SERVICIO
DELETE FROM EVALUACION_SERVICIO;

-- 8. CLIENTE (References SUCURSAL)
DELETE FROM CLIENTE;

-- 9. PRODUCTO (References TIPO_PRODUCTO)
DELETE FROM PRODUCTO;

-- 10. TIPO_PRODUCTO
DELETE FROM TIPO_PRODUCTO;

-- 11. SUCURSAL (References CIUDAD)
DELETE FROM SUCURSAL;

-- 12. CIUDAD (References PAIS)
DELETE FROM CIUDAD;

-- 13. PAIS
DELETE FROM PAIS;

COMMIT;
