-- Script to drop all tables respecting referential integrity (child tables first)

-- 1. REGISTRO_SINIESTRO (References SINIESTRO and REGISTRO_CONTRATO)
DROP TABLE IF EXISTS REGISTRO_SINIESTRO;

-- 2. SINIESTRO
DROP TABLE IF EXISTS SINIESTRO;

-- 3. METAS (References CLIENTE, PRODUCTO and CONTRATO)
DROP TABLE IF EXISTS METAS;

-- 4. REGISTRO_CONTRATO (References CONTRATO, PRODUCTO and CLIENTE)
DROP TABLE IF EXISTS REGISTRO_CONTRATO;

-- 5. CONTRATO
DROP TABLE IF EXISTS CONTRATO;

-- 6. RECOMIENDA (References CLIENTE, EVALUACION_SERVICIO and PRODUCTO)
DROP TABLE IF EXISTS RECOMIENDA;

-- 7. EVALUACION_SERVICIO
DROP TABLE IF EXISTS EVALUACION_SERVICIO;

-- 8. CLIENTE (References SUCURSAL)
DROP TABLE IF EXISTS CLIENTE;

-- 9. PRODUCTO (References TIPO_PRODUCTO)
DROP TABLE IF EXISTS PRODUCTO;

-- 10. TIPO_PRODUCTO
DROP TABLE IF EXISTS TIPO_PRODUCTO;

-- 11. SUCURSAL (References CIUDAD)
DROP TABLE IF EXISTS SUCURSAL;

-- 12. CIUDAD (References PAIS)
DROP TABLE IF EXISTS CIUDAD;

-- 13. PAIS
DROP TABLE IF EXISTS PAIS;
