CREATE TABLE DIM_CLIENTE (
    SK_DIM_CLIENTE INTEGER PRIMARY KEY,
    COD_CLIENTE INTEGER,
    NB_CLIENTE VARCHAR(25),
    CI_RIF VARCHAR(45),
    TELEFONO VARCHAR(45),
    DIRECCION VARCHAR(45),
    SEXO VARCHAR(45),
    EMAIL VARCHAR(45)
);

CREATE TABLE DIM_PRODUCTO (
    SK_DIM_PRODUCTO INTEGER PRIMARY KEY,
    COD_PRODUCTO INTEGER,
    NB_PRODUCTO VARCHAR(25),
    DESCRIP_PRODUCTO VARCHAR(25),
    COD_TIPO_PRODUCTO VARCHAR(25),
    NB_TIPO_PRODUCTO VARCHAR(25),
    CALIFICACION VARCHAR(25)
);

CREATE TABLE DIM_EVALUACION_SERVICIO (
    SK_DIM_EVALUACION_SERVICIO INTEGER PRIMARY KEY,
    COD_EVALUACION_SERVICIO INTEGER,
    NB_DESCRIP VARCHAR(25)
);

CREATE TABLE FACT_EVALUACION_SERVICIO (
    SK_DIM_CLIENTE INTEGER,
    SK_DIM_PRODUCTO INTEGER,
    SK_DIM_EVALUACION_SERVICIO INTEGER,
    CANTIDAD INTEGER,
    RECOMIENDA_AMIGO REAL,
    FOREIGN KEY (SK_DIM_CLIENTE) REFERENCES DIM_CLIENTE(SK_DIM_CLIENTE),
    FOREIGN KEY (SK_DIM_PRODUCTO) REFERENCES DIM_PRODUCTO(SK_DIM_PRODUCTO),
    FOREIGN KEY (SK_DIM_EVALUACION_SERVICIO) REFERENCES DIM_EVALUACION_SERVICIO(SK_DIM_EVALUACION_SERVICIO)
);