CREATE TABLE DIM_TIEMPO (
    SK_DIM_TIEMPO INTEGER PRIMARY KEY,
    COD_ANNIO INTEGER,
    COD_MES INTEGER,
    COD_DIA_ANNIO INTEGER,
    COD_DIA_MES INTEGER,
    COD_DIA_SEMANA INTEGER,
    COD_SEMANA INTEGER,
    DESC_DIA_SEMANA VARCHAR(10),
    DESC_DIA_SEMANA_CORTA VARCHAR(5),
    DESC_MES VARCHAR(20),
    DESC_MES_CORTA VARCHAR(3),
    DESC_TRIMESTRE INTEGER,
    DESC_SEMESTRE INTEGER,
    FECHA_COMPLETA DATE
);

CREATE TABLE DIM_CONTRATO (
    SK_DIM_CONTRATO INTEGER PRIMARY KEY,
    NRO_CONTRATO INTEGER,
    DESCRIP_CONTRATO VARCHAR(25)
);

CREATE TABLE DIM_SINIESTRO (
    SK_DIM_SINIESTRO INTEGER PRIMARY KEY,
    NRO_SINIESTRO INTEGER,
    DESCRIP_SINIESTRO VARCHAR(25)
);

CREATE TABLE DIM_CLIENTE (
    SK_DIM_CLIENTE INTEGER PRIMARY KEY,
    COD_CLIENTE INTEGER,
    NB_CLIENTE VARCHAR(25),
    CI_RIF VARCHAR(45),
    TELEFONO VARCHAR(45),
    DIRECCION VARCHAR(45),
    SEXO VARCHAR(45),
    EMAIL VARCHAR(45)
);

CREATE TABLE DIM_SUCURSAL (
    SK_DIM_SUCURSAL INTEGER PRIMARY KEY,
    COD_SUCURSAL INTEGER,
    NB_SUCURSAL VARCHAR(25),
    COD_CIUDAD VARCHAR(45),
    NB_CIUDAD VARCHAR(45),
    COD_PAIS VARCHAR(45),
    NB_PAIS VARCHAR(45)
);

CREATE TABLE DIM_PRODUCTO (
    SK_DIM_PRODUCTO INTEGER PRIMARY KEY,
    COD_PRODUCTO INTEGER,
    NB_PRODUCTO VARCHAR(25),
    DESCRIP_PRODUCTO VARCHAR(25),
    COD_TIPO_PRODUCTO VARCHAR(25),
    NB_TIPO_PRODUCTO VARCHAR(25),
    CALIFICACION VARCHAR(25)
);

CREATE TABLE FACT_REGISTRO_SINIESTRO (
    SK_FECHA_SINIESTRO INTEGER,
    SK_FECHA_RESPUESTA INTEGER,
    SK_DIM_CLIENTE INTEGER,
    SK_DIM_CONTRATO INTEGER,
    SK_DIM_SUCURSAL INTEGER,
    SK_DIM_PRODUCTO INTEGER,
    SK_DIM_SINIESTRO INTEGER,
    CANTIDAD INTEGER,
    MONTO_RECONOCIDO REAL,
    MONTO_SOLICITADO REAL,
    ID_RECHAZO CHAR(2),
    FOREIGN KEY (SK_FECHA_SINIESTRO) REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    FOREIGN KEY (SK_FECHA_RESPUESTA) REFERENCES DIM_TIEMPO(SK_DIM_TIEMPO),
    FOREIGN KEY (SK_DIM_CLIENTE) REFERENCES DIM_CLIENTE(SK_DIM_CLIENTE),
    FOREIGN KEY (SK_DIM_CONTRATO) REFERENCES DIM_CONTRATO(SK_DIM_CONTRATO),
    FOREIGN KEY (SK_DIM_SUCURSAL) REFERENCES DIM_SUCURSAL(SK_DIM_SUCURSAL),
    FOREIGN KEY (SK_DIM_PRODUCTO) REFERENCES DIM_PRODUCTO(SK_DIM_PRODUCTO),
    FOREIGN KEY (SK_DIM_SINIESTRO) REFERENCES DIM_SINIESTRO(SK_DIM_SINIESTRO)
);